### PR TITLE
Quick-fix for chatbubble

### PR DESCRIPTION
**Pull request by elizeuangelo**
Chatbubble wasn't working properly, this fix it

### CODE REVIEW

**Comment by kakaroto** [comment]
Ah, thanks! I hadn't noticed that you modified the chat bubble code when you moved it to the hook.
I also just noticed this : `message = game.messages.get(game.messages._source[game.messages._source.length-1]._id);`
Why are you doing that? the message is already received as argument to the method, why are you grabbing the last message instead?

**Comment by elizeuangelo** [comment]
Because foundry sends only the message.data.content as the message argument on the hook. You dont have an object but a string.

**Comment by kakaroto** [comment]
Ah ok, I remember now, that was the reason why I didn't use the hook when it was added to Foundry. I thought that was fixed, but I guess not.
I'm hesitating now on whether to keep it or revert to what I had before, because I don't like the idea of looking up the last message which may or may not be the one that the chat bubble refers to (think of a race condition of two messages arriving at the same time, since things happen async, it may be executed out of order).
Regardless, you shouldn't use `._source` as it's a private field, you should use `.entities`, also you don't need to get the message using the id of the message you already have...  so the line :
```js
message = game.messages.get(game.messages._source[game.messages._source.length-1]._id);
```
Would become : 
```js
message = game.messages.entities[game.messages.entities.length - 1];
```
I would rather do it this way though just to be extra safe : 
- Don't change the `message` variable from a string to an object within the function, that's confusing.
- Rename the argument into `messageContent` instead, so it would be more appropriate to what it actually is
- Get the last 10 messages and find the last one with the same content as what we received
```js
 chatBubble (token, html, messageContent, {emote}) {
     const message = game.messages.entities.slice(-10).reverse().find(m => m.data.content === messageContent);
```

**Comment by elizeuangelo** [comment]
Just keep in mind the chatBubble hook was required to change the message html. Without the html the text would get scrambled (still useful because players cant read it) but would not have the font.

I also dont like looking up for messages. =/

**Comment by kakaroto** [comment]
Ah thanks. That makes sense about html, i hadn't thought of that. So yeah, the hook is the only solution. Thanks! I'm merging it now, will test later!

**Pull request merged**
