### PR TITLE
chatBubble's window size + custom languages on actorsheets

### PR DESCRIPTION
**Pull request by elizeuangelo**
- Fixed the chatBubble's window size not being displayed correctly (this was a known issue);
- The module now also reads custom languages directly in actorsheets in 5e and pf1 and pf2e, no need to add a language for the world because of one NPC, lots of NPCs (and compendiums) now work correctly language-wise -> less work for the DM.

### CODE REVIEW

**Comment by kakaroto** [comment]
Thanks!
I did notice the bubble size being an issue, but it wasn't a big deal to me. I see what you're doing and I'm worried it may be a bit too complex for what it needs to be. What do you think of simply forcing the font size to 100% when inside the chat bubble ? Would that make more sense than doing dirty tricks and overriding the core code just to change the height ?
Would a simple `_getFontStyle(lang).replace(/[0-9]+%/, '100%')` work ?

**Comment by elizeuangelo** [comment]
It also affects the scrolling function and duration and some other functions the 'say' method calls in case big texts, in that sense its harmonic with the core foundry behavior: big texts will scroll down till read.

`_getFontStyle(lang).replace(/[0-9]+%/, '100%')` this would diminish a bit the problem but create others Not all fonts have the same size and some would appear too small and fonts with more width could still fall out screen. Big texts on small fonts would scroll down on 'empty text'.

But I agree with you this is a minor issue... I just tought the fix was easy enough. But honestly if not I believe a non-fix (letting the standard behavior as it is) may be better, at least no text will be too small and no empty scrolls.

Anyways, thank you for the feedback!

**Comment by kakaroto** [comment]
Ah I see, well thanks for that explanation. I though that a `100%` font was always going to be the same pixel height (16px) no matter what the font is. I know that some fonts will have bigger/smaller line height, but I was under the impression that with css, it was forcing them all to scale to a specific height with the font-size.
I see you edited your response to say that you tested and it seems to work. So I'm leaving it up to you, as I don't have time to test, let me know if you think using a 100% font size works and is better, or if you think overriding the function is the better solution.
Either way, I reviewed the code and I don't have any comments other than what I stated about font size.

(by the way, do you know if setting `style["font-size"] = "100%"` would work instead of doing that regular expression replace?)

**Comment by kakaroto** [comment]
Oh I see, checked the code and you're right. That sucks.
I think this should get filed as a foundry bug because it should use the html itself to find its dimensions, not the original message since the hook could modify the html in various ways.
One solution would be (with a comment to explain why this hack is necessary) : call `setTimeout(fixDimension, 0)`. 
Since there's no delay/async in the chatbubble.say, and the timeout is 0, it means it will execute right after it (or at least, as soon as possible after the function executes). In theory, there might be a millisecond where the size would flicker, but it wouldn't be visible to the user most of the time I suppose.

**Comment by elizeuangelo** [comment]
I tested and it kinda worked but its not only the `height`, its also the `width`, `top`, `left`, unmentioning duration and scrolling. The `dimensions` are used to calculate lots of other factors in these methods, some are setTimeouts in themselves wich we would need to override.

We could replicate foundry's entire new `say` method to make it right but we would just be increasing incompability instead of diminishing it?

**Comment by kakaroto** [comment]
Thanks for all the testing you've done. I hadn't thought of the scrolling/duration, so yes, that makes it more complicated instead of simplifying the solution. I wanted to see if there was an easy/cleaner solution but at this point, I think anything else is just going to be more complicated, so I've merged what you've done with the override of `_getDimensions`.

Thanks!

**Pull request merged**
